# Rakefile
include Rake::DSL
require 'bundler'
Bundler.require

Wox::Tasks.create :info_plist => 'Punisher/Punisher-Info.plist', :sdk => 'iphoneos', :configuration => 'Release' do
  build :debug, :configuration => 'Debug'

  build :release, :developer_certificate => 'iPhone Developer: ANTON KATKOV (258ED4Z7HA)' do
    ipa :app_store, :provisioning_profile => 'App Store'
    ipa :adhoc, :provisioning_profile => '8694132F-7A1A-4B2F-93D0-6764AC7DEE56' do
      testflight :publish, :api_token => 'af7140355be791bf7248083aab49f055_MTQzNzk0MjAxMS0wOC0zMSAwNjowMDoyMi40MzIzNjI',
                           :team_token => '2199c962071b6a7c893ae2b1a7ede7be_NDYzOTcyMDExLTEyLTA5IDA4OjMxOjE1Ljk1NjYyNw',
                           :notes => proc { File.read("CHANGELOG") },
                           :distribution_lists => %w[All],
                           :notify => true

    end
  end
end